# This file is not called Cargo.toml in order to allow
# using Fadroma as a Git submodule in repos that are
# already workspaces (because Cargo doesn't support
# nested workspaces). See `package.lock` for usage info.

[workspace]
members = [
  "crates/*",
]

[profile.release]
opt-level        = 3
debug            = false
rpath            = false
lto              = true
debug-assertions = false
codegen-units    = 1
panic            = 'abort'
incremental      = false
overflow-checks  = true
