[package]
name    = "fadroma-snip20-api"
version = "0.1.0"
edition = "2018"
authors = [
  "Adam A. <adam@hack.bg>",
  "Asparuh Kamenov <aakamenov@hack.bg>",
]

[lib]
path = "lib.rs"

[dependencies]
fadroma-platform-scrt = { path = "../fadroma-platform-scrt" }
secret-toolkit = { version = "0.3.0", default-features = false, features = ["snip20"] }
