[package]
name    = "fadroma-proc-message"
version = "0.1.0"
authors = ["Adam Avramov <adam@hack.bg>"]
edition = "2018"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
quote = "1.0"
proc-macro2 = "^1.0.20"
