[package]
name    = "fadroma-math"
version = "0.1.0"
edition = "2018"
authors = [
  "Adam A. <adam@hack.bg>",
  "Asparuh Kamenov <aakamenov@hack.bg>",
]

[lib]
path = "lib.rs"

[dependencies]
fadroma-platform-scrt = { path = "../fadroma-platform-scrt" }

primitive-types = { version = "0.9.1",   default-features = false }
serde           = { version = "1.0.103", default-features = false, features = ["derive"] }
